# Coolify 僅部署資料庫服務配置
# 此配置用於只部署 PostgreSQL 資料庫服務

version: '3.8'

services:
  # PostgreSQL 資料庫服務
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: casino
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d casino"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# Coolify 特定配置
x-coolify:
  # 服務配置
  services:
    database:
      port: 5432
      proxy:
        type: none  # 資料庫不需要外部訪問

  # 環境變數配置
  environment:
    # 必需的環境變數
    required:
      - POSTGRES_PASSWORD
    
    # 可選的環境變數
    optional:
      - POSTGRES_DB
      - POSTGRES_USER

  # 資源限制
  resources:
    database:
      memory: 512M
      cpu: 0.5

  # 備份配置
  backup:
    enabled: true
    schedule: "0 2 * * *"  # 每天凌晨2點備份
    retention: 7

  # 監控配置
  monitoring:
    enabled: true
    healthchecks: true
    logs:
      retention: 7d