# Coolify 僅部署前後端服務配置
# 此配置用於只部署前端和後端服務，不包含資料庫

version: '3.8'

services:
  # 後端 API 服務
  backend:
    image: ${BACKEND_IMAGE:-billyziiii/fullstack-docker-app-backend:latest}
    environment:
      NODE_ENV: production
      PORT: 5000
      # 使用外部資料庫連接（需要預先設置好資料庫）
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${FRONTEND_URL}
      HOST: 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # 前端應用服務
  frontend:
    image: ${FRONTEND_IMAGE:-billyziiii/fullstack-docker-app-frontend:latest}
    environment:
      VITE_API_URL: ${BACKEND_URL}/api
      PORT: 3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

# Coolify 特定配置
x-coolify:
  # 服務配置
  services:
    frontend:
      domains:
        - ${FRONTEND_DOMAIN}
      port: 2222
      proxy:
        type: traefik
        ssl: true
        redirect_to_https: true
    
    backend:
      domains:
        - ${BACKEND_DOMAIN}
      port: 5000
      proxy:
        type: traefik
        ssl: true
        redirect_to_https: true
        path_prefix: /api

  # 環境變數配置
  environment:
    # 必需的環境變數
    required:
      - DATABASE_URL  # 使用外部資料庫連接字串
      - JWT_SECRET
      - FRONTEND_DOMAIN
      - BACKEND_DOMAIN
      - FRONTEND_URL
      - BACKEND_URL
    
    # 可選的環境變數
    optional:
      - FRONTEND_IMAGE
      - BACKEND_IMAGE

  # 資源限制
  resources:
    backend:
      memory: 256M
      cpu: 0.3
    frontend:
      memory: 128M
      cpu: 0.2

  # 監控配置
  monitoring:
    enabled: true
    healthchecks: true
    logs:
      retention: 7d